"""Preset document records and file content, backed by bundled example files.

Loaded from ``_manifest.json`` at import time so installs don't pay for
a filesystem walk. The manifest is generated by ``tools/build.py`` from
the per-family ``README.md`` front-matter; CI validates it's up to
date on every PR.

Two primitives are exposed:

- :func:`doc_preset` — returns a fully-populated document record
  (``category``, ``description``, ``mime_type``, ``file_path``, ...),
  suitable for dropping into a seller's ``listing.json`` ``documents``
  map. This is the expansion the SDK applies to ``$preset`` JSON
  sentinels at upload time.

- :func:`file_preset` — returns the raw UTF-8 content of the bundled
  example file itself. Useful when the example isn't a listing
  document — for embedding as a code snippet, feeding to a test
  harness, or any future use that needs the bytes rather than the
  document metadata.

Both accept either a bare preset name (``"s3_connectivity_v1"``,
``"s3_connectivity"``) or a ``{"$preset": ..., "$with": ...}`` sentinel,
so the same function works from JSON walkers and from programmatic
Python code. Version-less aliases (``s3_connectivity``) resolve to the
latest published version in the family.

See https://github.com/unitysvc/unitysvc-sellers/issues/25 for design.
"""

from __future__ import annotations

import atexit
import hashlib
import json
import os
import tempfile
from copy import deepcopy
from importlib.resources import files as _files
from pathlib import Path
from typing import Any

from ._registry import preset

# Per-process directory for parameter-substituted preset bodies.  We
# hash the (preset_name, params) tuple so identical substitutions reuse
# the same file across calls — avoids accumulating thousands of
# byte-identical temp files when a long-running consumer expands the
# same preset for many listings.  The directory is registered for
# atexit cleanup so short-lived CLI processes (``usvc_data`` /
# ``usvc_seller``) don't leak.
_SUBSTITUTED_DIR: Path | None = None


def _substituted_dir() -> Path:
    """Return the per-process tmp dir for substituted preset bodies,
    creating it lazily on first use and registering atexit cleanup."""
    global _SUBSTITUTED_DIR
    if _SUBSTITUTED_DIR is None:
        _SUBSTITUTED_DIR = Path(
            tempfile.mkdtemp(prefix=f"unitysvc_data_{os.getpid()}_")
        )
        atexit.register(_cleanup_substituted_dir)
    return _SUBSTITUTED_DIR


def _cleanup_substituted_dir() -> None:
    """Best-effort recursive removal of the substituted-bodies dir.
    Called via atexit; swallow any error so we don't poison shutdown."""
    global _SUBSTITUTED_DIR
    if _SUBSTITUTED_DIR is None or not _SUBSTITUTED_DIR.is_dir():
        return
    try:
        for child in _SUBSTITUTED_DIR.iterdir():
            try:
                child.unlink()
            except OSError:
                pass
        _SUBSTITUTED_DIR.rmdir()
    except OSError:
        pass

# Resolved once at import time. Duplicated with __init__ rather than
# imported to avoid a circular import during package load. Use
# ``__package__`` (the parent package, "unitysvc_data") rather than
# ``__name__`` (the module, "unitysvc_data.presets") — Python 3.11's
# ``importlib.resources.files`` rejects module anchors; 3.12+ accepts
# both, but the package anchor is portable.
_EXAMPLES_ROOT = _files(__package__).joinpath("examples")

__all__ = [
    "PRESETS",
    "MANIFEST",
    "ALIASES",
    "OVERRIDABLE",
    "doc_preset",
    "file_preset",
    "list_presets",
    "register_jinja_globals",
]

# Fields a seller may override when expanding a preset. Everything else
# — category, mime_type, file_path — is tied to the bundled file
# content and rejected as an override.
OVERRIDABLE: frozenset[str] = frozenset({"description", "is_public", "is_active", "meta"})


def _load_manifest() -> dict[str, Any]:
    manifest_bytes = _files(__package__).joinpath("_manifest.json").read_bytes()
    return json.loads(manifest_bytes)


def _resolve_example_path(relative_file: str) -> str:
    target = _EXAMPLES_ROOT.joinpath(relative_file)
    if not target.is_file():
        raise FileNotFoundError(
            f"Manifest references missing file {relative_file!r}. "
            f"Rebuild with `python tools/build.py`."
        )
    return str(Path(str(target)))


MANIFEST: dict[str, Any] = _load_manifest()
_PRESET_RECORDS: dict[str, dict[str, Any]] = {}

# ``parameters`` is intentionally absent from ``_PRESET_RECORDS`` so it
# never leaks into the document record returned by ``doc_preset`` (which
# describes the listing-document, not the build-time substitution
# inputs).  It's stored here separately and consumed by ``file_preset``.
_PRESET_PARAMETERS: dict[str, dict[str, str]] = {}

for _name, _entry in MANIFEST["presets"].items():
    _PRESET_RECORDS[_name] = {
        "category": _entry["category"],
        "description": _entry["description"],
        "file_path": _resolve_example_path(_entry["example_file"]),
        "is_active": _entry["is_active"],
        "is_public": _entry["is_public"],
        "meta": dict(_entry.get("meta", {})),
        "mime_type": _entry["mime_type"],
    }
    # ``parameters`` was added in manifest schema v1.1 — older
    # manifests (or hand-built ones) may not have the field, so default
    # to no-parameters rather than raising.
    _PRESET_PARAMETERS[_name] = dict(_entry.get("parameters", {}))

# Alias entries share the same underlying record as their target. We
# store the record under both names so a lookup of either resolves in
# O(1) without chasing pointers.
ALIASES: dict[str, str] = dict(MANIFEST.get("aliases", {}))
for _alias, _target in ALIASES.items():
    if _target not in _PRESET_RECORDS:
        raise RuntimeError(
            f"_manifest.json alias {_alias!r} points at missing preset {_target!r}. "
            f"Rebuild with `python tools/build.py`."
        )
    _PRESET_RECORDS[_alias] = _PRESET_RECORDS[_target]
    _PRESET_PARAMETERS[_alias] = _PRESET_PARAMETERS[_target]


def _make_factory(record: dict[str, Any]):
    def _factory(**overrides: Any) -> dict[str, Any]:
        bad = set(overrides) - OVERRIDABLE
        if bad:
            raise ValueError(
                f"Cannot override {sorted(bad)!r} — these fields are tied to the file content. "
                f"Allowed overrides: {sorted(OVERRIDABLE)!r}"
            )
        out = deepcopy(record)
        for key, value in overrides.items():
            if key == "meta" and isinstance(value, dict) and isinstance(out.get("meta"), dict):
                out["meta"] = {**out["meta"], **value}
            else:
                out[key] = value
        return out

    return _factory


PRESETS: dict[str, Any] = {name: _make_factory(record) for name, record in _PRESET_RECORDS.items()}


# --- Source parsing --------------------------------------------------------


def _parse_source(source: Any) -> tuple[str, dict[str, Any], dict[str, str]]:
    """Normalise a preset reference to ``(name, overrides, params)``.

    Accepts either a bare name string or a sentinel dict
    ``{"$preset": ..., "$with": ..., "$params": ...}``.

    - ``$with`` carries metadata overrides for ``doc_preset`` (existing
      behaviour: description / is_public / is_active / meta).
    - ``$params`` carries substitution values for ``${__name__}``
      placeholders in the example file body, consumed by
      ``file_preset``.  Values must be strings; any name not declared
      in the preset's front-matter is rejected at substitution time.

    Returns ``(name, {}, {})`` for bare-string sources — callers supply
    overrides / params via kwargs instead.
    """
    if isinstance(source, str):
        return source, {}, {}

    if not isinstance(source, dict):
        raise TypeError(
            f"Expected a preset name string or a $preset sentinel dict, "
            f"got {type(source).__name__}"
        )

    if "$preset" not in source:
        raise ValueError(f"Node is not a preset sentinel (missing '$preset'): {source!r}")

    unknown = set(source) - {"$preset", "$with", "$params"}
    if unknown:
        raise ValueError(
            f"Unknown keys in preset sentinel: {sorted(unknown)!r}. "
            f"Only '$preset', '$with', and '$params' are allowed."
        )

    name = source["$preset"]
    if not isinstance(name, str):
        raise ValueError(f"'$preset' must be a string, got {type(name).__name__}")

    overrides = source.get("$with") or {}
    if not isinstance(overrides, dict):
        raise ValueError(f"'$with' must be an object, got {type(overrides).__name__}")

    params = source.get("$params") or {}
    if not isinstance(params, dict):
        raise ValueError(f"'$params' must be an object, got {type(params).__name__}")
    for k, v in params.items():
        if not isinstance(k, str):
            raise ValueError(f"'$params' key must be a string, got {type(k).__name__}: {k!r}")
        if not isinstance(v, str):
            raise ValueError(
                f"'$params' value for {k!r} must be a string "
                f"(got {type(v).__name__}: {v!r})"
            )

    return name, overrides, params


def _lookup(name: str, pool: dict[str, Any], what: str) -> Any:
    try:
        return pool[name]
    except KeyError:
        raise KeyError(
            f"Unknown preset: {name!r}. Available {what}s: {sorted(pool)!r}"
        ) from None


# --- Public API ------------------------------------------------------------


@preset
def doc_preset(source: Any, **kwargs: Any) -> dict[str, Any]:
    """Return a fully-populated document record for the named preset.

    Seller-facing usage is the flat form, dispatched via ``$doc_preset``
    in a parsed ``listing.json``::

        {"$doc_preset": "preset_name"}                         # bare
        {"$doc_preset": {"name": "x", "description": "..."}}   # flat overrides
        {"$doc_preset": {"name": "x", "version_prefix": "/v1"}}# flat parameters

    Keys other than ``name`` are auto-discriminated:

    - Names declared in the preset's front-matter ``parameters`` table
      are treated as substitution values for ``${__name__}`` references
      in the example body.  Substitution is applied eagerly: the
      rendered body is materialised to a per-process tmp file and
      ``file_path`` on the returned record points at it, so consumers
      reading ``file_path`` get the substituted output transparently.
    - Everything else is a metadata override (``description``,
      ``is_public``, ``is_active``, ``meta``).  Anything that's neither
      a declared parameter nor an OVERRIDABLE field raises.

    Build-time guarantees parameter names don't collide with metadata
    field names, so the discrimination is unambiguous.

    The returned dict is a fresh copy on every call; callers may mutate
    it freely.
    """
    name, sentinel_overrides, sentinel_params = _parse_source(source)

    if sentinel_overrides or sentinel_params:
        # Internal middle-layer sentinel form ({"$preset": ..., "$with":
        # ..., "$params": ...}).  Not seller-facing; preserved for
        # programmatic callers that prefer explicit separation.  Mixing
        # with kwargs would be ambiguous — pick one.
        if kwargs:
            raise ValueError(
                "Cannot combine keyword arguments with a sentinel-form "
                "'$with' / '$params' block — pick one."
            )
        metadata = sentinel_overrides
        params = sentinel_params
    else:
        # Flat form: split kwargs by checking each key against the
        # preset's declared parameters.  Any key not matching a declared
        # parameter falls through to the factory, which validates it
        # against OVERRIDABLE.
        declared = _PRESET_PARAMETERS.get(name, {})
        params = {k: v for k, v in kwargs.items() if k in declared}
        metadata = {k: v for k, v in kwargs.items() if k not in declared}

    # Validate param values are strings (matches sentinel-form check).
    for k, v in params.items():
        if not isinstance(v, str):
            raise ValueError(
                f"Parameter {k!r} value must be a string "
                f"(got {type(v).__name__}: {v!r})"
            )

    factory = _lookup(name, PRESETS, "preset")
    record = factory(**metadata)
    if params:
        # Substitute eagerly and redirect ``file_path`` at the rendered
        # output so consumers (upload pipeline, test runner) read the
        # substituted body without needing to know parameters exist.
        # The bundled source file remains untouched in the package; the
        # rendered version lives in a per-process tmp dir cleaned up on
        # interpreter exit.  Identical (preset, params) pairs reuse the
        # same tmp file via a content-addressed name.
        record["file_path"] = _materialise_substituted_body(
            preset_name=name,
            bundled_file_path=record["file_path"],
            params=params,
        )
        # No ``_params`` on the record — the seller's listing-document
        # schema validator rejects unknown fields, and now that
        # ``file_path`` points at the rendered body, params have no
        # downstream consumer anyway.
    return record


def _materialise_substituted_body(
    preset_name: str,
    bundled_file_path: str,
    params: dict[str, str],
) -> str:
    """Substitute ``params`` into the bundled preset body, write the
    result to a per-process tmp file, and return the tmp file's path.

    Uses a content-addressed filename so identical (preset, params)
    pairs share a single tmp file — short-circuits the read+write+sub
    on cache hit.  Preserves the original file's basename suffix so
    consumers that key on the extension (`.j2`, `.py.j2`, etc.) keep
    working.
    """
    declared = _PRESET_PARAMETERS.get(preset_name, {})
    bundled = Path(bundled_file_path)

    # Cache key: preset name + the params that survive after defaults
    # are applied.  Two callers passing different overrides that
    # resolve to the same effective values share a tmp file.
    resolved = {**declared, **params}
    fingerprint_src = json.dumps(
        {"preset": preset_name, "resolved": resolved},
        sort_keys=True,
    ).encode("utf-8")
    fingerprint = hashlib.sha256(fingerprint_src).hexdigest()[:16]

    # Preserve compound suffixes like ``.py.j2``, ``.sh.j2`` — Path.suffix
    # only returns the last segment so we slice manually.
    name_dots = bundled.name.split(".", 1)
    suffix = ("." + name_dots[1]) if len(name_dots) > 1 else ""
    out_path = _substituted_dir() / f"{preset_name}-{fingerprint}{suffix}"
    if out_path.is_file():
        # Cache hit — content is content-addressed by fingerprint, so
        # an existing file with this name is byte-identical to what
        # we'd produce.
        return str(out_path)

    content = bundled.read_text(encoding="utf-8")
    if declared:
        content = _substitute_params(content, declared, params, preset_name)
    out_path.write_text(content, encoding="utf-8")
    return str(out_path)


@preset
def file_preset(source: Any, **kwargs: Any) -> str:
    """Return the UTF-8 content of the preset's bundled file, with
    parameter substitution applied.

    Seller-facing usage matches :func:`doc_preset` — the flat form,
    auto-discriminated against the preset's declared parameters::

        file_preset("preset_name")                              # bare
        file_preset("preset_name", version_prefix="/v1")        # flat param

    Every ``${__name__}`` reference in the body is substituted; for
    any parameter the caller didn't supply, the preset's declared
    default is used.

    Unlike :func:`doc_preset`, ``file_preset`` does not accept metadata
    overrides — the file content's shape is fixed by the bundled file.
    Any kwarg that isn't a declared parameter raises.

    .. note::

       For Jinja2 templates (``.j2`` files), the returned string is
       the **raw template source after parameter substitution** —
       constructs like ``{% if local_testing %}`` and ``{{ var }}`` are
       preserved verbatim and rendered by the calling SDK at upload /
       test time.  Parameter substitution happens *before* Jinja2 sees
       the source, so ``${__name__}`` placeholders are pure text.
    """
    name, sentinel_overrides, sentinel_params = _parse_source(source)
    if sentinel_overrides:
        raise ValueError(
            "file_preset does not support metadata overrides — the file content is immutable. "
            "Use doc_preset() if you need a document record with per-field overrides."
        )
    if sentinel_params and kwargs:
        raise ValueError(
            "Cannot combine keyword parameters with a sentinel-form '$params' block — "
            "pick one."
        )

    declared = _PRESET_PARAMETERS.get(name, {})
    effective_params = dict(sentinel_params or kwargs)
    for k, v in effective_params.items():
        if not isinstance(v, str):
            raise ValueError(
                f"Parameter {k!r} value must be a string "
                f"(got {type(v).__name__}: {v!r})"
            )

    unknown = set(effective_params) - set(declared)
    if unknown:
        raise ValueError(
            f"Unknown parameter(s) {sorted(unknown)!r} for preset {name!r}. "
            f"Declared parameters: {sorted(declared) or 'none'}."
        )

    record = _lookup(name, _PRESET_RECORDS, "preset")
    content = Path(record["file_path"]).read_text(encoding="utf-8")
    if not declared:
        # Fast path: no parameters declared, no substitution needed.
        # Avoids regex traversal on the >50 existing presets that don't
        # use parameters.
        return content

    return _substitute_params(content, declared, effective_params, name)


def _substitute_params(
    content: str,
    declared: dict[str, str],
    overrides: dict[str, str],
    preset_name: str,
) -> str:
    """Substitute ``${__name__}`` placeholders for every declared
    parameter, in three steps:

    1. Build the resolved value map: declared defaults overlaid with
       caller-supplied overrides.
    2. For each ``(name, value)`` in the resolved map, replace every
       occurrence of ``${__name__}`` in the content with ``value``.
    3. Anything else (``${__not_declared__}``, ``${VAR}`` shell vars,
       ``{{ jinja }}`` markers) passes through verbatim — the loop
       only touches names that exist in the declared map.

    Best-effort by design.  Authors may have literal
    ``${__something__}`` strings for documentation, future-staged
    parameters, or any other reason; the resolver doesn't
    second-guess them.
    """
    resolved = {**declared, **overrides}
    for name, value in resolved.items():
        content = content.replace(f"${{__{name}__}}", value)
    return content


def list_presets() -> tuple[list[str], dict[str, str]]:
    """Return ``(versioned_names, aliases)``.

    *versioned_names* is the sorted list of concrete preset names
    (``s3_connectivity_v1``, ...); *aliases* maps each version-less
    family name to its current latest versioned name
    (``s3_connectivity`` → ``s3_connectivity_v1``).

    Symmetric with ``usvc_data list`` on the CLI.
    """
    return sorted(MANIFEST["presets"]), dict(ALIASES)


def register_jinja_globals(env: Any) -> None:
    """Register every preset factory as a Jinja2 global on *env*.

    Lets generated-repo templates write ``{{ s3_connectivity_v1() | tojson }}``
    directly in ``listing.json.j2`` instead of the ``$preset`` JSON
    sentinel. Hand-authored repos use the sentinel path and never need
    this hook.

    Both concrete names (``s3_connectivity_v1``) and aliases
    (``s3_connectivity``) are registered.
    """
    env.globals.update(PRESETS)
