"""Preset document records and file content, backed by bundled example files.

Loaded from ``_manifest.json`` at import time so installs don't pay for
a filesystem walk. The manifest is generated by ``tools/build.py`` from
the per-family ``README.md`` front-matter; CI validates it's up to
date on every PR.

Two primitives are exposed:

- :func:`doc_preset` — returns a fully-populated document record
  (``category``, ``description``, ``mime_type``, ``file_path``, ...),
  suitable for dropping into a seller's ``listing.json`` ``documents``
  map. This is the expansion the SDK applies to ``$preset`` JSON
  sentinels at upload time.

- :func:`file_preset` — returns the raw UTF-8 content of the bundled
  example file itself. Useful when the example isn't a listing
  document — for embedding as a code snippet, feeding to a test
  harness, or any future use that needs the bytes rather than the
  document metadata.

Both accept either a bare preset name (``"s3_connectivity_v1"``,
``"s3_connectivity"``) or a ``{"$preset": ..., "$with": ...}`` sentinel,
so the same function works from JSON walkers and from programmatic
Python code. Version-less aliases (``s3_connectivity``) resolve to the
latest published version in the family.

See https://github.com/unitysvc/unitysvc-sellers/issues/25 for design.
"""

from __future__ import annotations

import json
from copy import deepcopy
from importlib.resources import files as _files
from pathlib import Path
from typing import Any

from ._registry import preset

# Resolved once at import time. Duplicated with __init__ rather than
# imported to avoid a circular import during package load. Use
# ``__package__`` (the parent package, "unitysvc_data") rather than
# ``__name__`` (the module, "unitysvc_data.presets") — Python 3.11's
# ``importlib.resources.files`` rejects module anchors; 3.12+ accepts
# both, but the package anchor is portable.
_EXAMPLES_ROOT = _files(__package__).joinpath("examples")

__all__ = [
    "PRESETS",
    "MANIFEST",
    "ALIASES",
    "OVERRIDABLE",
    "doc_preset",
    "file_preset",
    "list_presets",
    "register_jinja_globals",
]

# Fields a seller may override when expanding a preset. Everything else
# — category, mime_type, file_path — is tied to the bundled file
# content and rejected as an override.
OVERRIDABLE: frozenset[str] = frozenset({"description", "is_public", "is_active", "meta"})


def _load_manifest() -> dict[str, Any]:
    manifest_bytes = _files(__package__).joinpath("_manifest.json").read_bytes()
    return json.loads(manifest_bytes)


def _resolve_example_path(relative_file: str) -> str:
    target = _EXAMPLES_ROOT.joinpath(relative_file)
    if not target.is_file():
        raise FileNotFoundError(
            f"Manifest references missing file {relative_file!r}. "
            f"Rebuild with `python tools/build.py`."
        )
    return str(Path(str(target)))


MANIFEST: dict[str, Any] = _load_manifest()
_PRESET_RECORDS: dict[str, dict[str, Any]] = {}

for _name, _entry in MANIFEST["presets"].items():
    _PRESET_RECORDS[_name] = {
        "category": _entry["category"],
        "description": _entry["description"],
        "file_path": _resolve_example_path(_entry["example_file"]),
        "is_active": _entry["is_active"],
        "is_public": _entry["is_public"],
        "meta": dict(_entry.get("meta", {})),
        "mime_type": _entry["mime_type"],
    }

# Alias entries share the same underlying record as their target. We
# store the record under both names so a lookup of either resolves in
# O(1) without chasing pointers.
ALIASES: dict[str, str] = dict(MANIFEST.get("aliases", {}))
for _alias, _target in ALIASES.items():
    if _target not in _PRESET_RECORDS:
        raise RuntimeError(
            f"_manifest.json alias {_alias!r} points at missing preset {_target!r}. "
            f"Rebuild with `python tools/build.py`."
        )
    _PRESET_RECORDS[_alias] = _PRESET_RECORDS[_target]


def _make_factory(record: dict[str, Any]):
    def _factory(**overrides: Any) -> dict[str, Any]:
        bad = set(overrides) - OVERRIDABLE
        if bad:
            raise ValueError(
                f"Cannot override {sorted(bad)!r} — these fields are tied to the file content. "
                f"Allowed overrides: {sorted(OVERRIDABLE)!r}"
            )
        out = deepcopy(record)
        for key, value in overrides.items():
            if key == "meta" and isinstance(value, dict) and isinstance(out.get("meta"), dict):
                out["meta"] = {**out["meta"], **value}
            else:
                out[key] = value
        return out

    return _factory


PRESETS: dict[str, Any] = {name: _make_factory(record) for name, record in _PRESET_RECORDS.items()}


# --- Source parsing --------------------------------------------------------


def _parse_source(source: Any) -> tuple[str, dict[str, Any]]:
    """Normalise a preset reference to ``(name, overrides)``.

    Accepts either a bare name string or a ``{"$preset": ..., "$with": ...}``
    sentinel dict. Returns ``(name, {})`` for string sources since
    bare-name callers supply overrides as kwargs instead.
    """
    if isinstance(source, str):
        return source, {}

    if not isinstance(source, dict):
        raise TypeError(
            f"Expected a preset name string or a $preset sentinel dict, "
            f"got {type(source).__name__}"
        )

    if "$preset" not in source:
        raise ValueError(f"Node is not a preset sentinel (missing '$preset'): {source!r}")

    unknown = set(source) - {"$preset", "$with"}
    if unknown:
        raise ValueError(
            f"Unknown keys in preset sentinel: {sorted(unknown)!r}. "
            f"Only '$preset' and '$with' are allowed."
        )

    name = source["$preset"]
    if not isinstance(name, str):
        raise ValueError(f"'$preset' must be a string, got {type(name).__name__}")

    overrides = source.get("$with") or {}
    if not isinstance(overrides, dict):
        raise ValueError(f"'$with' must be an object, got {type(overrides).__name__}")

    return name, overrides


def _lookup(name: str, pool: dict[str, Any], what: str) -> Any:
    try:
        return pool[name]
    except KeyError:
        raise KeyError(
            f"Unknown preset: {name!r}. Available {what}s: {sorted(pool)!r}"
        ) from None


# --- Public API ------------------------------------------------------------


@preset
def doc_preset(source: Any, **overrides: Any) -> dict[str, Any]:
    """Return a fully-populated document record for the named preset.

    ``source`` may be a bare preset name (``"s3_connectivity_v1"`` or
    the version-less alias ``"s3_connectivity"``) or a JSON sentinel
    ``{"$preset": ..., "$with": {...}}`` as it appears in a parsed
    ``listing.json``.

    Overrides (``description``, ``is_active``, ``is_public``, ``meta``)
    may come from ``$with`` when using the sentinel form or from
    keyword arguments when passing a bare name — but not both at once.
    Attempting to override ``category``, ``mime_type``, or ``file_path``
    raises :class:`ValueError` because those are tied to the bundled
    file content.

    The returned dict is a fresh copy on every call; callers may
    mutate it freely.
    """
    name, sentinel_overrides = _parse_source(source)
    if sentinel_overrides and overrides:
        raise ValueError(
            "Cannot combine keyword overrides with a $preset sentinel's '$with' block — "
            "pick one."
        )
    factory = _lookup(name, PRESETS, "preset")
    return factory(**(sentinel_overrides or overrides))


@preset
def file_preset(source: Any) -> str:
    """Return the raw UTF-8 content of the preset's bundled file.

    ``source`` may be a bare preset name or a ``$preset`` sentinel.
    Overrides are rejected because file content is immutable — use
    :func:`doc_preset` if you need a document record with per-field
    overrides.

    .. note::

       For Jinja2 templates (``.j2`` files), the returned string is
       the **raw template source** — constructs like
       ``{% if local_testing %}`` are preserved verbatim. Rendering
       requires listing / interface / provider context that only the
       calling SDK knows; the sellers SDK applies that rendering via
       ``render_template_file`` at upload time. If you're piping the
       content to a runnable file (e.g.
       ``usvc_data file-preset ... > smoke.py``) and the preset
       targets a ``.j2`` file, you'll get a template, not an
       executable script.
    """
    name, sentinel_overrides = _parse_source(source)
    if sentinel_overrides:
        raise ValueError(
            "file_preset does not support '$with' overrides — the file content is immutable. "
            "Use doc_preset() if you need a document record with per-field overrides."
        )
    record = _lookup(name, _PRESET_RECORDS, "preset")
    return Path(record["file_path"]).read_text(encoding="utf-8")


def list_presets() -> tuple[list[str], dict[str, str]]:
    """Return ``(versioned_names, aliases)``.

    *versioned_names* is the sorted list of concrete preset names
    (``s3_connectivity_v1``, ...); *aliases* maps each version-less
    family name to its current latest versioned name
    (``s3_connectivity`` → ``s3_connectivity_v1``).

    Symmetric with ``usvc_data list`` on the CLI.
    """
    return sorted(MANIFEST["presets"]), dict(ALIASES)


def register_jinja_globals(env: Any) -> None:
    """Register every preset factory as a Jinja2 global on *env*.

    Lets generated-repo templates write ``{{ s3_connectivity_v1() | tojson }}``
    directly in ``listing.json.j2`` instead of the ``$preset`` JSON
    sentinel. Hand-authored repos use the sentinel path and never need
    this hook.

    Both concrete names (``s3_connectivity_v1``) and aliases
    (``s3_connectivity``) are registered.
    """
    env.globals.update(PRESETS)
